### ISSUE TITLE
Where is fetch defined?

### ISSUE THREAD

**Issue by seanmtracey** [Financial-Times/next-myft-client#109]
https://github.com/Financial-Times/next-myft-client/blob/master/src/myft-api.js#L73

**Comment by leggsimon** [comment]
We define `fetch` globally in `n-router`

**Comment by seanmtracey** [comment]
Is that wise? If I require a module that depends on fetch being declared globally, but I don't want to do such a thing in my application, I'd have to manually change the imported code.
